FROM node:22-bookworm

RUN apt-get update && apt-get install -y \
    wkhtmltopdf \
    # Limpieza
    && rm -rf /var/lib/apt/lists/*
    
WORKDIR /app

RUN npm install -g pnpm

COPY package.json package-lock.json ./

RUN pnpm install

COPY . .

RUN pnpm build

CMD ["pnpm", "start:prod"]