FROM node:22 as base

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libnss3 \
    libnspr4 \
    libatk1.0-0 \
    libatk-bridge2.0-0 \
    libcups2 \
    libdrm2 \
    libxkbcommon0 \
    libxcomposite1 \
    libxdamage1 \
    libxfixes3 \
    libxrandr2 \
    libgbm1 \
    libasound2 \
    && rm -rf /var/lib/apt/lists/*

RUN npm install -g pnpm

COPY . .

RUN pnpm fetch
RUN pnpm install
RUN npx puppeteer browsers install chrome

CMD pnpm build; pnpm start:dev;